# Generated by Django 6.0 on 2025-12-11 15:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
        ('properties', '0002_room_properties__status_2b3c4f_idx_and_more'),
        ('tenancies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='tenancy',
            index=models.Index(fields=['status'], name='tenancies_t_status_ccb6f0_idx'),
        ),
        migrations.AddIndex(
            model_name='tenancy',
            index=models.Index(fields=['start_date'], name='tenancies_t_start_d_986f2c_idx'),
        ),
        migrations.AddIndex(
            model_name='tenancy',
            index=models.Index(fields=['end_date'], name='tenancies_t_end_dat_3a9858_idx'),
        ),
        migrations.AddIndex(
            model_name='tenancy',
            index=models.Index(fields=['-created_at'], name='tenancies_t_created_a4e039_idx'),
        ),
    ]
