# Generated by Django 6.0

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancies', '0002_tenancy_tenancies_t_status_ccb6f0_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='tenancy',
            index=models.Index(fields=['room', 'status'], name='tenancies_room_status_idx'),
        ),
        migrations.AddIndex(
            model_name='tenancy',
            index=models.Index(fields=['tenant', 'status'], name='tenancies_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='tenancy',
            index=models.Index(fields=['status', 'end_date'], name='tenancies_status_end_date_idx'),
        ),
    ]

