# Generated by Django 6.0 on 2025-12-14 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenancies', '0003_add_composite_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='tenancy',
            name='tenancies_room_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='tenancy',
            name='tenancies_tenant_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='tenancy',
            name='tenancies_status_end_date_idx',
        ),
    ]
