# Generated by Django 6.0 on 2025-12-11 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('tenancies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='tenancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='tenancies.tenancy'),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='billing.invoice'),
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('tenancy', 'period')},
        ),
    ]
