# Generated by Django 6.0 on 2025-12-14 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_add_composite_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='invoice',
            name='billing_inv_status_period_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='billing_inv_tenancy_period_idx',
        ),
    ]
