# Generated by Django 6.0 on 2025-12-11 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['status'], name='properties__status_2b3c4f_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['floor'], name='properties__floor_d3b022_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['-created_at'], name='properties__created_748d28_idx'),
        ),
    ]
