# Generated by Django 6.0 on 2025-12-11 14:06

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_type', models.CharField(choices=[('electricity', 'Điện'), ('water', 'Nước'), ('internet', 'Internet'), ('cleaning', 'Vệ sinh'), ('parking', 'Đỗ xe'), ('other', 'Khác')], default='other', max_length=50)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit', models.CharField(default='', max_length=20)),
                ('is_recurring', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_prices', to='properties.property')),
            ],
            options={
                'unique_together': {('property', 'service_type')},
            },
        ),
    ]
