# Generated by Django 6.0 on 2025-12-11 14:06

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0001_initial'),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period', models.CharField(max_length=7)),
                ('electricity_old', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('electricity_new', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('water_old', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('water_new', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('source', models.CharField(choices=[('manual', 'Nhập tay'), ('ocr', 'OCR')], default='manual', max_length=20)),
                ('ocr_payload', models.JSONField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ocr_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meter_images', to='files.fileasset')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meter_readings', to='properties.room')),
            ],
            options={
                'ordering': ['-period', 'room'],
                'unique_together': {('room', 'period')},
            },
        ),
    ]
