# Generated by Django 6.0 on 2025-12-11 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
        ('metering', '0001_initial'),
        ('properties', '0002_room_properties__status_2b3c4f_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='meterreading',
            index=models.Index(fields=['period'], name='metering_me_period_8b4a97_idx'),
        ),
        migrations.AddIndex(
            model_name='meterreading',
            index=models.Index(fields=['source'], name='metering_me_source_9e9fe9_idx'),
        ),
        migrations.AddIndex(
            model_name='meterreading',
            index=models.Index(fields=['-created_at'], name='metering_me_created_1647b1_idx'),
        ),
    ]
