# Generated by Django 6.0

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metering', '0002_meterreading_metering_me_period_8b4a97_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='meterreading',
            index=models.Index(fields=['room', 'period'], name='metering_room_period_idx'),
        ),
        migrations.AddIndex(
            model_name='meterreading',
            index=models.Index(fields=['period', '-created_at'], name='metering_period_created_idx'),
        ),
    ]

