# Generated by Django 6.0 on 2025-12-14 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metering', '0003_add_composite_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='meterreading',
            name='metering_room_period_idx',
        ),
        migrations.RemoveIndex(
            model_name='meterreading',
            name='metering_period_created_idx',
        ),
    ]
