# Generated by Django 6.0 on 2025-12-11 14:06

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=500)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('purpose', models.CharField(choices=[('contract', 'Contract'), ('meter', 'Meter'), ('maintenance', 'Maintenance')], default='contract', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
