# Generated by Django 6.0 on 2025-12-12 02:50

import files.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fileasset',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='fileasset',
            name='path',
        ),
        migrations.AddField(
            model_name='fileasset',
            name='file',
            field=models.FileField(default=None, max_length=500, upload_to=files.models.upload_to),
            preserve_default=False,
        ),
    ]
