# Generated by Django 6.0 on 2025-12-13 16:25

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('status_change', 'Status Change'), ('login', 'Login'), ('logout', 'Logout'), ('view', 'View'), ('export', 'Export'), ('other', 'Other')], max_length=20)),
                ('model_name', models.CharField(max_length=100)),
                ('object_id', models.UUIDField(blank=True, null=True)),
                ('object_repr', models.CharField(blank=True, max_length=255)),
                ('changes', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='audit_audit_created_6e540c_idx'), models.Index(fields=['user'], name='audit_audit_user_id_292c79_idx'), models.Index(fields=['model_name'], name='audit_audit_model_n_515731_idx'), models.Index(fields=['action_type'], name='audit_audit_action__dd3a3c_idx'), models.Index(fields=['model_name', 'object_id'], name='audit_audit_model_n_20c0d3_idx')],
            },
        ),
    ]
